# Generated by Django 6.1 on 2026-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0002_bookmark_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="complete",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
